---
title: "DataViz Makeover 3"
description: |
  DataViz Makeover 3 provides a do-over for an existing data visualisation created to reveal the spatio-temporal patterns of armed conflict in selected South-east Asia countries.
author:
  - name: Ng Wee Kien (Vincent)
    url: https://www.linkedin.com/in/ngweekiensg/
date: 03-18-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 1.0 Section A
Critique the interactive data visualisation from its clarity, aesthetics and interactivity. At least 2 from each evaluation criterion.

### 1.1 Clarity

| S/N | Comments | Suggested Improvements |
|-----|---------------------------|-------------------------------------|
| C1 | Regarding the points plotted on the map visual, it is not clear if it represents the number of events, or the number of fatalities. | Indicate explicitly in the title of the map visual whether the data being visualized refers to number of events or fatalities. |
| C2 | The datapoints plotted on the map are of constant size, which does not provide much information on the scale or impact of the event. | Scale the size of the points by the value, whether it is the number of events or fatalities. |
| C3 | While the various line plots help to denote the trend across the years, users are not able to gauge the breakdown of the scale of various events in relation to each other. | To plot the various event types on a single plot. This allows users to have a sense of which events are major and minor contributors across the time period. |

### 1.2 Aesthetics

| S/N | Comments | Suggested Improvements |
|-----|---------------------------|-------------------------------------|
| A1 | For the various data points on the map, it is unclear if that specific event had any fatalities or not.  | Introduce point symbols, where a circle denotes an event without any fatalities, and a cross denotes the presence of fatalities for that recorded event. |
| A2 | There are no vertical gridlines present on the line plot. When more years are selected, this could make it tougher for the user to interpret the chart. | Add dotted vertical grid lines to aid the user in interpreting the chart, especially when making sense of the trend across many years. |
| A3 |  | XXX |

### 1.3 Interactivity

| S/N | Comments | Suggested Improvements |
|-----|---------------------------|-------------------------------------|
| I1 | XXX. | XXX. |
| I2 | XXX. | XXX. |
| I3 | XXX | XXX |



# 2.0 Section B
Suggest alternative data visualisation and interactive techniques to improve the current design. 



# 3.0 Section C
Using Tableau, design the proposed data visualization.




# 4.0 Section D
Provide step-by-step description on how the data visualization was prepared.




# 5.0 Section E
Describe five major observations revealed by the data visualization prepared.


















